CREATE DATABASE IF NOT EXISTS students_db;
USE students_db;
CREATE TABLE IF NOT EXISTS students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  age INT NOT NULL,
  address TEXT NOT NULL
);
